--- 
configurations_1: 
  name: site_name
  value: Flowplace
  configuration_type: string
  description: "The name of the site.  This is used all over the place"
configurations_2:
  name: welcome_text
  value: <h1>Welcome to the Flowplace!</h1>
  configuration_type: text
  description: HTML that shows up on the home-page if no-one is logged in.
configurations_3:
  name: footer
  value: The Flowplace is licensed under the <a href="http://www.gnu.org/licenses/gpl.html">GPL</a>
  configuration_type: text
  description: HTML block for the footer.
configurations_4:
  name: new_user_policy
  value: admin_create
  configuration_type: "options(self_signup,admin_create)"
  description: The site policy on how new users are added to the system
configurations_5:
  name: circle_currency_policy
  value: self_authorize
  configuration_type: "options(self_authorize,admin_authorize)"
  description: The site policy on authorization for managing currencies and circles
configurations_6:
  name: global_banner
  value: 
  configuration_type: text
  description: This html text will appear across the top of the site and is dismissable once you log-in.  Used for demo/dev site warinings.
configurations_7:
  name: analytics
  value: 
  configuration_type: string
  description: Google Analytics html block.
configurations_8:
  name: autojoin
  value: 
  configuration_type: yaml
  description: "Autojoin yaml specification. (Enter: circles: name1,name2,...)"
configurations_9:
  name: wealing_policy
  value: "on"
  configuration_type: "options(on,off)"
  description: "Policy for activating the wealing interface."
configurations_10:
  name: single_circle
  value: "off"
  configuration_type: "options(on,off)"
  description: "Activate single-circle simplified user interface."
configurations_11:
  name: default_language
  value: "en"
  configuration_type: "options(en,fr,es)"
  description: "Choose the default language for new users."